name: 🧮 GitHub Metrics

on:
  schedule: [{ cron: "0 0 * * 0" }]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: sinhasandeep2006
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata

          plugin_languages: yes
          plugin_lines: yes
          plugin_habits: yes
          plugin_achievements: no


          # ✅ This saves metrics.svg into your repo
          output_action: commit
          committer_token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
